SELECT RANKING AS "구분", 
		MAX(day1) AS "월요일",
		MAX(day2) AS "화요일",
		MAX(day3) AS "수요일",
		MAX(day4) AS "목요일",
		MAX(day5) AS "금요일",
		MAX(day6) AS "토요일",
		MAX(day7) AS "일요일"
from
(
	SELECT   RANKING
			,CASE WHEN DAYOFTHEWEEK = 0 AND MENU_NM IS NOT NULL THEN MENU_NM ELSE '-' END AS day1
			,CASE WHEN DAYOFTHEWEEK = 1 AND MENU_NM IS NOT NULL THEN MENU_NM ELSE '-' END AS day2
			,CASE WHEN DAYOFTHEWEEK = 2 AND MENU_NM IS NOT NULL THEN MENU_NM ELSE '-' END AS day3
			,CASE WHEN DAYOFTHEWEEK = 3 AND MENU_NM IS NOT NULL THEN MENU_NM ELSE '-' END AS day4
			,CASE WHEN DAYOFTHEWEEK = 4 AND MENU_NM IS NOT NULL THEN MENU_NM ELSE '-' END AS day5
			,CASE WHEN DAYOFTHEWEEK = 5 AND MENU_NM IS NOT NULL THEN MENU_NM ELSE '-' END AS day6
			,CASE WHEN DAYOFTHEWEEK = 6 AND MENU_NM IS NOT NULL THEN MENU_NM ELSE '-' END AS day7
	FROM
	(
		SELECT DAYOFTHEWEEK, MENU_NM, COUNT(*) AS COUNT, ROW_NUMBER() OVER (PARTITION BY DAYOFTHEWEEK ORDER BY COUNT(*) DESC, MENU_NM ) AS RANKING
		FROM
		(
			SELECT WEEKDAY(LOG_TKTM) AS DAYOFTHEWEEK , 
					MENU_NM  
			FROM kakaobank.menu_log
			WHERE MENU_NM != 'login' AND MENU_NM != 'logout'
		)  AS menu
		GROUP BY DAYOFTHEWEEK, MENU_NM
	) menu_RANKING
	WHERE RANKING <= 10
	GROUP BY RANKING, DAYOFTHEWEEK
) top_menu
GROUP BY RANKING
