SELECT  USR_LOG.USR_NO AS "사용자 번호"
		,CASE WHEN SUBSTRING(RSDT_NO,7,1) = 1 OR SUBSTRING(RSDT_NO,7,1)=3 THEN '남' WHEN SUBSTRING(RSDT_NO,7,1) = 2 OR SUBSTRING(RSDT_NO,7,1) = 4 THEN '여' ELSE '-' END AS "성별"
        ,CASE WHEN SUBSTRING(RSDT_NO,7,1) = 1 OR SUBSTRING(RSDT_NO,7,1)=2 THEN YEAR('20200626') - YEAR(CONCAT('19', SUBSTRING(RSDT_NO,1,6))) -(DATE_FORMAT(CONCAT('19', SUBSTRING(RSDT_NO,1,6)), '%m%d') >DATE_FORMAT('20200626', '%m%d') )  
        WHEN SUBSTRING(RSDT_NO,7,1) = 3 OR SUBSTRING(RSDT_NO,7,1) = 4 THEN YEAR('20200626') - YEAR(CONCAT('20', SUBSTRING(RSDT_NO,1,6))) -(DATE_FORMAT(CONCAT('20', SUBSTRING(RSDT_NO,1,6)), '%m%d') >DATE_FORMAT('20200626', '%m%d') )  else '-' END AS "나이"
        ,CASE WHEN LOC_NM IS NOT NULL THEN LOC_NM ELSE '-' END AS "이전 지역명"
		,CASE WHEN MCCO_NM IS NOT NULL THEN MCCO_NM ELSE '-' END AS "이동통신사명"
        ,CREATE_DATE AS "가입일"
        ,MODE_MENU_NM AS "최빈메뉴"
        ,LATEST_MENU_NM AS "최신메뉴"
FROM
(
	SELECT RSDT_NO.USR_NO, RSDT_NO, LOC_NM, MCCO_NM , CREATE_DATE
	FROM
	(
		SELECT USR_NO, RSDT_NO, LOG_TKTM, ROW_NUMBER () OVER (PARTITION BY USR_NO ORDER BY LOG_TKTM DESC) AS RAN
		FROM kakaobank.usr_info_chg_log
		WHERE RSDT_NO != ''
	) RSDT_NO
	LEFT OUTER JOIN
	(
		SELECT USR_NO, LOC_NM, LOG_TKTM, ROW_NUMBER () OVER (PARTITION BY USR_NO ORDER BY LOG_TKTM DESC) AS RAN
		FROM kakaobank.usr_info_chg_log
		WHERE LOC_NM != ''
	) LOC_NM
	ON RSDT_NO.USR_NO = LOC_NM.USR_NO AND RSDT_NO.RAN=1 AND LOC_NM.RAN=1
	LEFT OUTER JOIN
	(
		SELECT USR_NO, MCCO_NM, LOG_TKTM, ROW_NUMBER () OVER (PARTITION BY USR_NO ORDER BY LOG_TKTM DESC) AS RAN
		FROM kakaobank.usr_info_chg_log
		WHERE MCCO_NM != ''
	)  MCCO_NM
	ON RSDT_NO.USR_NO = MCCO_NM.USR_NO AND RSDT_NO.RAN=1 AND MCCO_NM.RAN=1
    LEFT OUTER JOIN
    (
		SELECT USR_NO, SUBSTRING(MIN(LOG_TKTM),1,8) AS CREATE_DATE
		FROM kakaobank.usr_info_chg_log
		GROUP BY USR_NO    
    ) CREATE_DATE
    ON RSDT_NO.USR_NO = CREATE_DATE.USR_NO
) USR_LOG
LEFT OUTER JOIN
(
	SELECT A. USR_NO,  MODE_MENU_NM, LATEST_MENU_NM
	FROM
	(
		SELECT  USR_NO, MENU_NM as LATEST_MENU_NM
		FROM
		(
			SELECT USR_NO, LOG_TKTM, MENU_NM, ROW_NUMBER() OVER (PARTITION BY USR_NO ORDER BY LOG_TKTM DESC) as RAN
			FROM kakaobank.menu_log
			WHERE MENU_NM != 'login' and MENU_NM != 'logout'
		) LATEST_MENU_NM
		where RAN=1
	) A
	LEFT OUTER JOIN
	(
		SELECT USR_NO, MENU_NM AS MODE_MENU_NM
		FROM
		(
			SELECT USR_NO, MENU_NM , ROW_NUMBER () OVER (PARTITION BY USR_NO ORDER BY COUNT(*) DESC) AS RAN
			FROM kakaobank.menu_log
			WHERE MENU_NM != 'login' and MENU_NM != 'logout'
			GROUP BY USR_NO, MENU_NM
		) MODE_MENU_NM
		WHERE RAN =1
	) B
	ON A.USR_NO =B.USR_NO
) MENU_LOG
ON MENU_LOG.USR_NO= USR_LOG.USR_NO